### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by niknoproblems** [kensk8er/chicksexer#4]
Message from pip:

```
Could not find a version that satisfies the requirement tensorflow==1.0.1 (from chicksexer) (from versions: 0.12.1, 1.0.0, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0)
No matching distribution found for tensorflow==1.0.1 (from chicksexer)
```

**Comment by oa98105** [comment]
Collecting chicksexer
  Using cached chicksexer-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-M6oXU5/chicksexer/setup.py", line 34, in <module>
        requirements = open('requirements.txt', 'r').read().splitlines()
      File "/usr/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by jakubtuchol** [comment]
@niknoproblems What version of Python are you using? I ran into this issue a couple of days ago, and it was because I was using Python 3.7, which is not yet supported by Tensorflow. I solved this issue by downgrading to Python 3.6.

**Comment by Mengyuliu0520** [comment]
> Message from pip:
> 
> ```
> Could not find a version that satisfies the requirement tensorflow==1.0.1 (from chicksexer) (from versions: 0.12.1, 1.0.0, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0)
> No matching distribution found for tensorflow==1.0.1 (from chicksexer)
> ```
Same problem, since the neural network structure was given, considering write the classifier my self.

**Comment by danyaljj** [comment]
Same problem here (using python 3.7).

**Comment by ZeegCL** [comment]
Same problem here with Python 3.7

**Comment by chaibialaa** [comment]
Same problem here with Python 3.7
